// Checks Gemini's token accounting in a run's raw records (NOTEBOOK.md,
// anomaly A3): whether totalTokens leaves thinking tokens out, and how many
// thinking tokens there are next to the visible output tokens.
// Usage, from the repo root: bun research/pilot/harness/check-tokens.ts <run_id>
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { RESULTS_DIR, repoRel } from "./paths.ts";
import { listRecordFiles, readRecord } from "./store.ts";

if (import.meta.main) {
  const runId = process.argv[2];
  if (!runId) throw new Error("Usage: bun research/pilot/harness/check-tokens.ts <run_id>");
  let steps = 0, totalEqualsInputPlusOutput = 0, stepsWithReasoning = 0, reasoningTokens = 0, outputTokens = 0, withRawUsage = 0;
  for (const file of listRecordFiles(runId)) {
    const r = readRecord(file);
    const turns = r.kind === "control" ? [r.turn] : r.kind === "trial" ? [r.turn1, ...r.branches.map((b: any) => b.turn)] : r.branches.map((b: any) => b.turn);
    for (const t of turns) for (const s of t?.steps ?? []) {
      steps++;
      const u = s.usage;
      if (u.totalTokens === u.inputTokens + u.outputTokens) totalEqualsInputPlusOutput++;
      const rt = u.outputTokenDetails?.reasoningTokens ?? u.reasoningTokens ?? 0;
      if (rt > 0) stepsWithReasoning++;
      reasoningTokens += rt;
      outputTokens += u.outputTokens ?? 0;
      if (s.providerMetadata?.google?.usageMetadata) withRawUsage++;
    }
  }
  const lines = [
    `# Token accounting check: \`${runId}\``,
    "",
    "Generated by `research/pilot/harness/check-tokens.ts` from the raw records.",
    "",
    "| measure | value |",
    "|---|---|",
    `| steps | ${steps} |`,
    `| steps where totalTokens = inputTokens + outputTokens | ${totalEqualsInputPlusOutput} |`,
    `| steps with reasoning (thinking) tokens | ${stepsWithReasoning} |`,
    `| reasoning tokens, all steps | ${reasoningTokens} |`,
    `| output tokens, all steps | ${outputTokens} |`,
    `| steps whose providerMetadata carries Google's raw usageMetadata | ${withRawUsage} |`,
    "",
  ];
  const out = join(RESULTS_DIR, runId, "token_accounting_check.md");
  writeFileSync(out, lines.join("\n"));
  console.log(`wrote ${repoRel(out)}`);
}
