// Milestone 1: full trials with a fake model at the real workspace root, to
// exercise every file operation (fault, snapshot, ten branch archives,
// restores) and measure the longest path. Also writes the exact system
// prompts and one example of each condition's messages from a fake turn 1.
// No API calls. Usage, from the repo root: bun research/pilot/harness/fake-trial.ts
import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "bun";
import { Budget } from "./cost.ts";
import { captureEnvironment } from "./environment.ts";
import { stamp, writeEvidence } from "./evidence.ts";
import { obedientAgent } from "./fake-model.ts";
import { CONDITIONS, CONDITION_NAMES } from "./history.ts";
import { nextIds } from "./ids.ts";
import { WS_DIR, assertRunFromRepoRoot, repoRel } from "./paths.ts";
import { prepareShell } from "./shell-env.ts";
import { runTrial, type RunContext, type TrialRecord } from "./trial.ts";
import type { FaultId } from "./faults.ts";

export function allPaths(root: string): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      out.push(full);
      if (statSync(full).isDirectory()) walk(full);
    }
  };
  walk(root);
  return out;
}

function trialFootprint(trialId: string): string[] {
  return [
    ...allPaths(join(WS_DIR, trialId)),
    ...allPaths(join(WS_DIR, "_stash", trialId)),
    ...allPaths(join(WS_DIR, "_snap", trialId)),
    join(WS_DIR, "_logs", `${trialId}.jsonl`),
  ];
}

function examples(r: TrialRecord): string {
  const lines = [
    "# System prompts and condition messages from a fake turn 1",
    "",
    `Generated by \`research/pilot/harness/fake-trial.ts\` from fake trial \`${r.trialId}\` (fault ${r.fault}, fake model, no API call).`,
    "Everything below is the harness's own record of what it sent, copied out of the trial record.",
    "",
    `cwd given to the model: \`${r.cwd}\``,
    "",
    `- P_full sha256: \`${r.prompts.pFullSha256}\``,
    `- P_norule sha256: \`${r.prompts.pNoRuleSha256}\``,
    "",
    "## P_full (C4, C5)",
    "",
    "```text",
    r.prompts.pFull,
    "```",
    "",
    "## P_norule (turn 1, C1, C2, C3)",
    "",
    "```text",
    r.prompts.pNoRule,
    "```",
    "",
    "## Turn 1 messages",
    "",
    "```json",
    JSON.stringify(r.turn1!.messages, null, 2),
    "```",
    "",
    "## A1_text (the fake model's turn-1 content, as easycode would store it)",
    "",
    "```text",
    r.turn1!.finalText,
    "```",
    "",
  ];
  for (const c of CONDITIONS) {
    const b = r.branches.find((x) => x.id === `V1_${c}`)!;
    lines.push(
      `## ${c} ${CONDITION_NAMES[c]} (variant V1)`,
      "",
      `System prompt: ${b.turn!.system === r.prompts.pFull ? "P_full" : b.turn!.system === r.prompts.pNoRule ? "P_norule" : "OTHER (bug)"}`,
      "",
      "```json",
      JSON.stringify(b.turn!.messages, null, 2),
      "```",
      "",
    );
  }
  const v2 = r.branches.find((x) => x.id === "V2_C5")!;
  lines.push(
    "## V2 example (C5): only the last user message changes",
    "",
    "```json",
    JSON.stringify(v2.turn!.messages.at(-1), null, 2),
    "```",
    "",
  );
  return lines.join("\n");
}

if (import.meta.main) {
  assertRunFromRepoRoot();
  prepareShell();
  const at = stamp();
  const faults: FaultId[] = ["F02", "F01"];
  const ids = nextIds(WS_DIR, "x", faults.length);
  const ctx: RunContext = {
    runId: `fake-${at}`,
    wsRoot: WS_DIR,
    budget: new Budget(1),
    versions: (() => {
      const e = captureEnvironment().code;
      return { easycodeCommit: e.easycodeCommitRunAgainst, harnessCommit: e.harnessCommit, harnessDirty: e.harnessDirty };
    })(),
    stop: { requested: false },
  };
  const summary = [];
  for (const [i, fault] of faults.entries()) {
    const r = await runTrial(ctx, {
      trialId: ids[i]!,
      fault,
      rep: 1,
      subject: { model: { requestedId: "fake-model", provider: "google", model: obedientAgent() }, pricingModelId: "gemini-2.5-flash" },
    });
    const paths = trialFootprint(r.trialId);
    const longest = paths.reduce((a, b) => (b.length > a.length ? b : a), "");
    const archives = r.branches.map((b) => b.archive.map((a) => repoRel(a.to)));
    const record = writeEvidence("m1", `fake_trial_${r.trialId}_${fault}_${at}.json.gz`, gzipSync(Buffer.from(JSON.stringify(r))));
    summary.push({
      trialId: r.trialId,
      fault,
      turn1: r.runtimeValidity.state,
      branches: r.branches.map((b) => `${b.id}:${b.state}`),
      archives,
      pathCount: paths.length,
      longestPath: longest,
      longestPathLength: longest.length,
      under200: longest.length < 200,
      record: repoRel(record),
    });
    if (fault === "F01") {
      const ex = writeEvidence("m1", `condition_examples_${r.trialId}_${at}.md`, examples(r));
      console.log(`examples: ${repoRel(ex)}`);
    }
    console.log(`${r.trialId} ${fault}: turn1 ${r.runtimeValidity.state}; ${r.branches.filter((b) => b.state === "RAN").length}/10 branches ran; longest path ${longest.length} chars`);
  }
  const out = writeEvidence("m1", `fake_trials_${at}.json`, JSON.stringify({ summary }, null, 2));
  console.log(`evidence: ${repoRel(out)}`);
  const worst = Math.max(...summary.map((s) => s.longestPathLength));
  console.log(`longest path overall: ${worst} chars`);
  process.exit(worst < 200 && summary.every((s) => s.branches.every((b) => b.endsWith(":RAN"))) ? 0 : 1);
}
