// Measured cost per turn-1 run, per branch and per control from a run's
// summary.csv, and the projected cost of the full pilot (brief, Milestone 2).
// Usage, from the repo root: bun research/pilot/harness/project-cost.ts <run_id>
//
// The projection assumes each other model uses the same input and output
// token counts per unit as the measured model, priced at its own rates from
// SUPPORTED_CHAT_MODELS. That assumption is stated in the output; it is a
// projection, not a measurement.
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parseCsv } from "./csv.ts";
import { pricingFor } from "./cost.ts";
import { FAULT_IDS } from "./faults.ts";
import { RESULTS_DIR, RUNS_DIR, repoRel } from "./paths.ts";
import { ALLOWED_MODELS, DEFAULTS } from "./run.ts";

type R = Record<string, string>;
const num = (r: R, f: string) => Number(r[f]) || 0;
const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : NaN);
const max = (xs: number[]) => (xs.length ? Math.max(...xs) : NaN);
const usd = (x: number) => (Number.isNaN(x) ? "n/a" : `$${x.toFixed(4)}`);

export function projectCost(runId: string, runsRoot = RUNS_DIR, resultsRoot = RESULTS_DIR): string {
  const summaryPath = join(resultsRoot, runId, "summary.csv");
  const manifest = JSON.parse(readFileSync(join(runsRoot, runId, "manifest.json"), "utf8"));
  const rows = parseCsv(readFileSync(summaryPath, "utf8"));
  const measuredModel: string = manifest.settings.models[0];
  // Every priced row that reached the model, whatever its outcome: all were paid for
  const paid = rows.filter((r) => r.priced === "1" && num(r, "input_tokens") > 0);
  const units = {
    "turn 1": paid.filter((r) => r.unit === "turn1"),
    branch: paid.filter((r) => r.unit === "branch"),
    control: paid.filter((r) => r.unit === "control"),
  };
  const spent = rows.reduce((s, r) => s + num(r, "cost_usd"), 0);
  const per = Object.fromEntries(
    Object.entries(units).map(([k, rs]) => [k, {
      n: rs.length,
      cost: mean(rs.map((r) => num(r, "cost_usd"))),
      maxCost: max(rs.map((r) => num(r, "cost_usd"))),
      input: mean(rs.map((r) => num(r, "input_tokens"))),
      output: mean(rs.map((r) => num(r, "output_tokens"))),
      reasoning: mean(rs.map((r) => num(r, "reasoning_tokens"))),
      billedOutput: mean(rs.map((r) => num(r, "billed_output_tokens"))),
    }]),
  ) as Record<keyof typeof units, { n: number; cost: number; maxCost: number; input: number; output: number; reasoning: number; billedOutput: number }>;

  // Full design (Section 4.6), upper bound: every turn 1 valid, so 10 branches each
  const reps = DEFAULTS.reps;
  const counts = { "turn 1": FAULT_IDS.length * reps, branch: FAULT_IDS.length * reps * 10, control: DEFAULTS.controlsPerType * 2 };
  const perModel = ALLOWED_MODELS.map((m) => {
    const p = pricingFor(m);
    const unitCost = (u: keyof typeof units) =>
      m === measuredModel ? per[u].cost : (per[u].input * p.inputUsdPerMillionTokens + per[u].billedOutput * p.outputUsdPerMillionTokens) / 1e6;
    const total = (Object.keys(counts) as (keyof typeof units)[]).reduce((s, u) => s + counts[u] * unitCost(u), 0);
    return { m, basis: m === measuredModel ? "measured cost per unit" : `${measuredModel}'s tokens per unit x ${m} prices`, t1: unitCost("turn 1"), br: unitCost("branch"), ct: unitCost("control"), total };
  });
  const grand = perModel.reduce((s, x) => s + x.total, 0);

  const lines = [
    `# Cost: measured in \`${runId}\` and projected for the full pilot`,
    "",
    `Generated by \`research/pilot/harness/project-cost.ts\` from \`${repoRel(summaryPath)}\`. Every number below comes from that file and the price table in easycode's SUPPORTED_CHAT_MODELS.`,
    "",
    `Spent in this run: **${usd(spent)}** (all rows, including infra errors).`,
    "",
    "## Measured per unit",
    "",
    "| unit | n | mean cost | max cost | mean input tokens | mean output tokens | mean reasoning tokens | mean billed output tokens |",
    "|---|---|---|---|---|---|---|---|",
    ...(Object.keys(units) as (keyof typeof units)[]).map((u) => {
      const x = per[u];
      return `| ${u} | ${x.n} | ${usd(x.cost)} | ${usd(x.maxCost)} | ${x.input.toFixed(0)} | ${x.output.toFixed(0)} | ${x.reasoning.toFixed(0)} | ${x.billedOutput.toFixed(0)} |`;
    }),
    "",
    "## Projection for the full pilot (Section 4.6)",
    "",
    `Upper bound on units per model: ${counts["turn 1"]} turn-1 runs, ${counts.branch} branches (every turn 1 valid), ${counts.control} controls; REPS = ${reps}.`,
    "",
    `Assumptions: the measured faults (${manifest.settings.faults.join(", ")}) stand for all ten; for the models not measured here, the token counts per unit equal ${measuredModel}'s and only the prices differ. ${measuredModel}'s counts include its thinking tokens, and those models run without easycode thinking settings, so their real counts may differ in either direction. These are projections, not measurements.`,
    "",
    "| model | basis | per turn 1 | per branch | per control | projected total |",
    "|---|---|---|---|---|---|",
    ...perModel.map((x) => `| ${x.m} | ${x.basis} | ${usd(x.t1)} | ${usd(x.br)} | ${usd(x.ct)} | ${usd(x.total)} |`),
    `| **all models** | | | | | **${usd(grand)}** |`,
    "",
    `Against BUDGET_USD ${manifest.settings.budgetUsd}: projected total ${usd(grand)}, which is ${grand <= manifest.settings.budgetUsd ? "within" : "OVER"} the budget. Spend before this run was ${usd(manifest.settings.spentBeforeRunUsd)}.`,
    "",
  ];
  const out = join(resultsRoot, runId, "cost_projection.md");
  mkdirSync(join(resultsRoot, runId), { recursive: true });
  if (existsSync(out) && readFileSync(out, "utf8") !== lines.join("\n")) throw new Error(`${repoRel(out)} exists and differs; move it aside first`);
  writeFileSync(out, lines.join("\n"));
  return out;
}

if (import.meta.main) {
  const runId = process.argv[2];
  if (!runId) throw new Error("Usage: bun research/pilot/harness/project-cost.ts <run_id>");
  console.log(`wrote ${repoRel(projectCost(runId))}`);
}
