// Milestone 1 fault validation (brief, Section 4.2). For each fault: inject,
// run the test command through the real bash tool and check the expected
// error; fix, run again and check the PASS line carries the new token.
// No model calls. Usage, from the repo root:
//   bun research/pilot/harness/validate-faults.ts
import { join } from "node:path";
import { createFixture, newNonce, tokenFor } from "./fixture.ts";
import { FAULTS, FAULT_IDS, applyFix, type FaultId } from "./faults.ts";
import { captureEnvironment } from "./environment.ts";
import { stamp, writeEvidence } from "./evidence.ts";
import { WS_DIR, assertRunFromRepoRoot, repoRel, trialPaths } from "./paths.ts";
import { prepareShell } from "./shell-env.ts";
import { callTool, instrumentedTools, type ToolEvent } from "./tools.ts";
import { mkdirSync } from "node:fs";

const TEST_COMMAND = "bash scripts/run_tests.sh";

function errorText(result: any): string {
  return typeof result?.error === "string" ? result.error : String(result?.stderr ?? "");
}

export async function validateFault(wsRoot: string, id: FaultId) {
  const fault = FAULTS[id];
  const paths = trialPaths(wsRoot, id);
  const nonce0 = newNonce();
  createFixture(paths.project, nonce0);
  mkdirSync(paths.stash, { recursive: true });
  const faultPaths = { project: paths.project, stash: paths.stash };
  const events: ToolEvent[] = [];

  const injectOps = await fault.inject(faultPaths);
  const brokenTools = instrumentedTools(paths.project, { disableBash: fault.disablesBash }, events);
  const before = await callTool(brokenTools, "bash", { command: TEST_COMMAND }, `${id}-before`);
  const beforeText = errorText(before);
  const failedAsExpected =
    fault.expected.test(beforeText) && (before.exitCode === undefined ? typeof before.error === "string" : before.exitCode !== 0);

  // Side probes: what the file tools and git see while the fault is in place
  const probes: Record<string, unknown> = {};
  if (id === "F02") probes.readFile = await callTool(brokenTools, "readFile", { path: "README.md" }, "F02-readFile");
  if (id === "F07") probes.gitToplevel = await callTool(brokenTools, "bash", { command: "git rev-parse --show-toplevel" }, "F07-git");

  const fix = await applyFix(fault, faultPaths);
  const fixedTools = instrumentedTools(paths.project, { disableBash: false }, events);
  const after = await callTool(fixedTools, "bash", { command: TEST_COMMAND }, `${id}-after`);
  const verbose = await callTool(fixedTools, "bash", { command: `${TEST_COMMAND} --verbose` }, `${id}-verbose`);
  const passLine = `RESULT: PASS 7/7 token=${fix.token}`;
  const lastLine = (s: string) => s.trimEnd().split(/\r?\n/).at(-1) ?? "";
  const passedWithNewToken =
    after.exitCode === 0 && lastLine(after.stdout) === passLine && fix.token !== tokenFor(nonce0);
  const verboseLines = String(verbose.stdout ?? "").trimEnd().split(/\r?\n/);
  const verboseOk =
    verbose.exitCode === 0 && verboseLines.length === 8 && verboseLines.slice(0, 7).every((l) => /^ok \d - /.test(l)) && verboseLines[7] === passLine;

  return {
    id,
    name: fault.name,
    kind: fault.kind,
    project: repoRel(paths.project),
    expectedError: fault.expected.source,
    inject: injectOps,
    before,
    failedAsExpected,
    probes,
    fix,
    after,
    passedWithNewToken,
    verbose,
    verboseOk,
    ok: failedAsExpected && passedWithNewToken && verboseOk,
    events,
  };
}

function summary(results: Awaited<ReturnType<typeof validateFault>>[]): string {
  const rows = results.map((r) => {
    const err = errorText(r.before).trim().split(/\r?\n/).join(" / ");
    return `| ${r.id} | ${r.name} | ${r.failedAsExpected ? "yes" : "NO"} | \`${err.replace(/\|/g, "\\|")}\` | ${r.passedWithNewToken ? "yes" : "NO"} | \`${String(r.after.stdout).trim()}\` | ${r.verboseOk ? "yes" : "NO"} |`;
  });
  return [
    "# Fault validation",
    "",
    "Generated by `research/pilot/harness/validate-faults.ts`. Each fault is injected into a fresh fixture, the",
    "test command runs through easycode's real bash tool, then the fix is applied and the command runs again.",
    "",
    "| Fault | Name | Failed as expected | Error seen | Passed after fix with new token | Output after fix | `--verbose` ok |",
    "|---|---|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

if (import.meta.main) {
  assertRunFromRepoRoot();
  const shellPrep = prepareShell();
  const at = stamp();
  const wsRoot = join(WS_DIR, "_m1", `faults-${at}`);
  const results = [];
  for (const id of FAULT_IDS) results.push(await validateFault(wsRoot, id));
  const allOk = results.every((r) => r.ok);
  const json = writeEvidence(
    "m1",
    `fault_validation_${at}.json`,
    JSON.stringify({ environment: captureEnvironment(), gitCeiling: shellPrep.gitCeiling, allOk, results }, null, 2),
  );
  const md = writeEvidence("m1", `fault_validation_${at}.md`, summary(results));
  for (const r of results) console.log(`${r.ok ? "ok  " : "FAIL"} ${r.id} ${r.name}`);
  console.log(`evidence: ${repoRel(json)}\n          ${repoRel(md)}`);
  process.exit(allOk ? 0 : 1);
}
